#!/usr/bin/env bash

export CONTECO_LABEL="module.kafka_connect_tocloud - ContEco"
export CONTECO_DESCRIPTION="Kafka Connect to cloud module with managed standard URL."

export CONTECO_TYPE="module"
export CONTECO_NAME="kafka_connect_tocloud"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
